#########################
#### common settings ####
#########################
spring:
  application:
    name: "webclients-spring-boot-example-service"

#####################
#### Swagger doc ####
#####################
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8090

#####################
#### Actuator properties ####
#####################
management:
  endpoints:
    web:
      exposure:
        include:
          - httptrace
          - info
          - health
          - prometheus
          - refresh
          - metrics
          - configprops
      base-path: /actuator
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
    health:
      show-details: always

#####################
#### Local profile ####
#####################
---
spring:
  config:
    activate:
      on-profile: "local"

externalservice:
  postcodeio-api:
    baseUrl: https://api.postcodes.io
    token: "test12455"

  starwars-api:
    baseUrl: https://swapi-graphql.netlify.app

#####################
#### Dev profile ####
#####################
---
spring:
  config:
    activate:
      on-profile: "dev"

externalservice:
  postcodeio-api:
    baseUrl: https://api.postcodes.io
    token: "test12455"

  starwars-api:
    baseUrl: https://swapi-graphql.netlify.app


#####################
#### Prod profile ####
#####################
---
spring:
  config:
    activate:
      on-profile: "prod"

externalservice:
  postcodeio-api:
    baseUrl: https://api.postcodes.io
    token: "test12455"

  starwars-api:
    baseUrl: https://swapi-graphql.netlify.app
